### PR TITLE
fix(deps): change dependency inorichi.injekt to uy.kohesive.injekt

### PR DESCRIPTION
**Pull request by raonsama**
The Issue: #1776

### CODE REVIEW

**Comment by Secozzi** [comment]
inorichi's injekt is different from kohesive's, you would need to address the differences as well

**Comment by abdallahmehiz** [comment]
We should use Koin

**Comment by Secozzi** [comment]
> We should use Koin

Wouldn't that break every existing extension?

**Comment by raonsama** [comment]
problem has been fixed with [this](https://github.com/mihonapp/mihon/commit/83fd4746eda1b99f35292b0c2211e606a421b3eb)

**Comment by jmir1** [comment]
c929854ae98b874bf1a7aceb82a15fbe3fb6a41f

**Pull request closed without merging**
