### PR TITLE
Mocha Theme

### PR DESCRIPTION
**Pull request by joelschmol**
Screenshot_20230920-082252
Screenshot_20230920-082326
Screenshot_20230920-082320
Screenshot_20230920-082258

### CODE REVIEW

**Comment by Quickdesh** [comment]
Looks good, but I am not a fan of the name

**Comment by joelschmol** [comment]
Yeah I'm not good with names

**Comment by Quickdesh** [comment]
Saffron is more orange and red.
I can see coffee as the name

**Comment by Quickdesh** [comment]
I like Mocha

**Comment by joelschmol** [comment]
Do i rename it?

**Comment by joelschmol** [comment]
Would

**Comment by Quickdesh** [comment]
Yeah, thats what I was going for since it matches the color scheme

**Comment by joelschmol** [comment]
should i rename it and create a PR again?

**Comment by Quickdesh** [comment]
No need to make a new PR, just add another commit to this branch

**Pull request closed without merging**
