### PR TITLE
fix libs.android.shortcut.gradle not found

### PR DESCRIPTION
**Pull request by Dark25**

### CODE REVIEW

**Comment by Secozzi** [comment]
Unable to replicate, are you sure it's not some issue on your end? Instead of changing build.gradle.kts, could you try specifing the hash in libs.versions.toml in case it was just some cache issue?

**Comment by abdallahmehiz** [comment]
> Unable to replicate, are you sure it's not some issue on your end? Instead of changing build.gradle.kts, could you try specifing the hash in libs.versions.toml in case it was just some cache issue?

i think i faced this issue sometime ago on a private project... It fixed itself after a few days. and since it's only happening on Github actions, it may be a problem with their SDKs.

**Comment by Dark25** [comment]
> > Unable to replicate, are you sure it's not some issue on your end? Instead of changing build.gradle.kts, could you try specifing the hash in libs.versions.toml in case it was just some cache issue?
> 
> i think i faced this issue sometime ago on a private project... It fixed itself after a few days. and since it's only happening on Github actions, it may be a problem with their SDKs.

In fact, they have deleted the Marven repo, which is why it does not download it. This did not happen to me until I made a version change in my branch.

**Comment by Dark25** [comment]
> > Unable to replicate, are you sure it's not some issue on your end? Instead of changing build.gradle.kts, could you try specifing the hash in libs.versions.toml in case it was just some cache issue?
> 
> i think i faced this issue sometime ago on a private project... It fixed itself after a few days. and since it's only happening on Github actions, it may be a problem with their SDKs.

In fact, they have deleted the Marven repo, which is why it does not download it. This did not happen to me until I made a version change in my branch.

**Comment by abdallahmehiz** [comment]
This PR is kind of obsolete now. Can we close it?

**Pull request closed without merging**
