### PR TITLE
fix: Manga extension settings crash

### PR DESCRIPTION
**Pull request by Samfun75**

### CODE REVIEW

**Review by Quickdesh — APPROVED** [review]

**Review by Claudemirovsky — APPROVED** [review]
bruh

**Comment by pjueon** [comment]
> ~~Wait no, this file is not to be changed~~
> 
> ~~This is the Source file that is copied over from tachiyomi.~~
> 
> ~~They don't use MangaSource, they just call it Source.~~
> 
> ~~Changing this would not let users access manga extensions~~

@Quickdesh 
Hi, I have a question question.
Could this PR somehow cause the issue #1153?

**Comment by abdallahmehiz** [comment]
> @Quickdesh Hi, I have a question question. Could this PR somehow cause the issue #1153?
no

**Comment by pjueon** [comment]
@abdallahmehiz 
Thanks for the confirmation.

**Pull request merged**
