### PR TITLE
Cotton Candy Theme

### PR DESCRIPTION
**Pull request by joelschmol**
Screenshot_20230920-082357
Screenshot_20230920-082355
Screenshot_20230920-082344
Screenshot_20230920-082340

### CODE REVIEW

**Comment by Quickdesh** [comment]
Could you add some screenshots?
It would make it easier to look into the colors.

**Comment by Quickdesh** [comment]
Looks good, suitable name too

**Comment by joelschmol** [comment]
Shoutout zerobun

**Comment by Quickdesh** [comment]
One last thing before I merge, and I need you to do the same thing for both colors. Could you shift the string for the name of the colors to strings-aniyomi.xml instead?

**Comment by joelschmol** [comment]
remove them from strings.xml and keep in strings-aniyomi.xml?

**Comment by Quickdesh** [comment]
Yes, shift the name of the string to the aniyomi file, for both colors

**Pull request closed without merging**
