### PR TITLE
Allows the user to hide categories.

### PR DESCRIPTION
**Pull request by logickoder**
Allows the user to hide some selected categories from the home screen

### Allows the user to hide hidden categories from the list of categories tab for extra security 🫡
image

### The visibility icon button toggles the visibility of the category in the home/libraries tab. If the hide hidden categories switch is turned on, hidden categories are not shown here
image

### Hidden categories are not shown in the libraries tab
image

### CODE REVIEW

**Comment by Quickdesh** [comment]
Great stuff

**Comment by Quickdesh** [comment]
But one more change. All the strings that you made for hiding, could you shift them to strings-aniyomi.xml

Since that is the file used for Aniyomi strings. You can comment out a new category for all the strings

**Comment by logickoder** [comment]
Okay, will do soon and push

**Comment by logickoder** [comment]
@Quickdesh done

**Comment by Quickdesh** [comment]
Yup just checked, thanks!

Have started the build, hopefully your IDE changes has not messed with ktlint

**Pull request merged**
